Event_Management/urls.py
from django.contrib import admin

from django.urls import path
from Tasty import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.dashboard),
    path('home/',views.index),
    path('singup/',views.sign_up,name='singup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.User_logout,name='logout'),
    path('menu/',views.menu),
    path('event',views.event),
    path('about',views.about),
    path('aboutus',views.aboutus),
    path('service',views.service),
    path('contact/',views.contact),
    path('booking',views.booking),
    path('bookingstatus',views.booking_status),
    path('delete_booking/<int:pk>', views.delete_booking,name='delete_booking'),
    # admin
    path('admin_dashboard',views.admin_dashboard),
    path('customer_view',views.customer_view),
    path('delete_customer_view/<int:pk>', views.delete_customer_view,name='delete_customer_view'),
    path('contactlist',views.contact_views),
    path('delete_contact_list/<int:pk>', views.delete_contact_list,name='delete_contact_list'),
    path('admin_menu/',views.admin_menu),
    path('admin_event',views.admin_event),
    path('view_booking',views.view_booking),
    path('approve-request/<int:pk>', views.approve_request_view,name='approve-request'),
    path('reject-request/<int:pk>', views.disapprove_request_view,name='reject-request'),
    
    
]

Tasty/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    phone = models.CharField(max_length=12)
    desc = models.TextField()
    date = models.DateField()
    def __str__(self):
        return self.name
class Booking(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    f_name=models.CharField(max_length=200)
    date =models.DateField(auto_now=False, auto_now_add=False)
    number=models.BigIntegerField(blank=False)
    status = models.CharField(max_length=100,default='Pending')
    venue=models.CharField(max_length=100,blank=True)
    day=models.IntegerField(blank=True)
    guest=models.IntegerField(blank=True)
   

    def __str__(self):
        return self.user.username

Tasty/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Contact
from django.core import validators
class SignUpForm(UserCreationForm):
    password2=forms.CharField(label='Confirm Password',widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        labels={'email':'Email','first_name':'First Name','last_name':'Last Name'}
class ContactusForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.CharField()
    desc = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'rows': 3, 'cols': 30}))
    phone=forms.CharField()

def mobile_no(value):
  mobile = str(value)
  if len(mobile) != 10:
    raise forms.ValidationError("Mobile Number Should 10 digit")
  
  
# class StuForm(forms.Form):
#   mob = forms.IntegerField(
#     validators =[mobile_no])
class BookingForm(forms.Form):

    Event_Name=forms.CharField(max_length=50)
    date=forms.DateField(required=False)
    Number=forms.NumberInput()

templates/about1.html
{% load static %}
{% include 'header.html' %}
<head>
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    
</head>
<section class="about section bd-container" id="about">
    <div class="about__container  bd-grid">
        <div class="about__data">
            <span class="section-subtitle about__initial">About us</span>
            <h2 class="section-title about__initial">We cook the best <br> tasty food</h2>
            <p class="about__description">We cook the best food in the entire city, with excellent customer service, the best meals and at the best price, visit us.</p>
            <a href="#" class="button">Explore history</a>
        </div>

        <!-- <img src="assets/img/about.jpg" alt="" class="about__img"> -->
        <div class="slideshow-container">

            <!-- Full-width images with number and caption text -->
            <div class="mySlides fade">
              <!-- <div class="numbertext"></div> -->
              <img src="{% static 'foodimage/hd1.jpg' %}" style="width:500px; height: 500px; object-fit:cover; border-radius: 16px;">
              <div class="text">Thai Steamed Fish</div>
            </div>
          
            <div class="mySlides fade">
              <!-- <div class="numbertext">2 / 3</div> -->
              <img src="{% static 'foodimage/hd2.jpg' %}" style="width:500px; height: 500px; object-fit:cover; border-radius: 16px;">
              <div class="text">Burgur</div>
            </div>
          
            <div class="mySlides fade">
              <!-- <div class="numbertext">3 / 3</div> -->
              <img src="{% static 'foodimage/hd3.jpg' %}" style="width:500px ; height: 500px; object-fit:cover; border-radius: 16px;">
              <div class="text">Roasted chicken</div>
            </div>
          </div>
    </div>
</section>


{% include 'footer.html' %}

<!--========== SCROLL REVEAL ==========-->
<script src="https://unpkg.com/scrollreveal"></script>

<!--========== MAIN JS ==========-->
<script src="{% static 'js/main.js' %}"></script>
<script>
    let slideIndex = 0;
            showSlides();

            function showSlides() {
             let i;
            let slides = document.getElementsByClassName("mySlides");
            for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
            }
            slideIndex++;
             if (slideIndex > slides.length) {slideIndex = 1}
            slides[slideIndex-1].style.display = "block";
            setTimeout(showSlides, 3000); // Change image every 2 seconds
            }
</script>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href='{% static "css/styles.css" %}'>
    <title>Document</title>
</head>
<body>
    <a href="#" class="scrolltop" id="scroll-top">
        <i class='bx bx-chevron-up scrolltop__icon'></i>
    </a>
<header class="l-header" id="header">
            <nav class="nav bd-container">
                <a href="/" class="nav__logo">Tasty</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="/" class="nav__link active-link">Home</a></li>
                        <li class="nav__item"><a href="/about" class="nav__link">About</a></li>

                        <li class="nav__item"><a href="/contact" class="nav__link">Contact us</a></li>
                        <li class="nav__item" ><a href="/singup" class="nav__link" >Signup</a></li>
                        <li class="nav__item"><a href="/login" class="nav__link">Login</a></li>
                        <li><i class='bx bx-moon change-theme' id="theme-button"></i></li>

                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
            </header>
            <script src="{% static 'js/main.js' %}"></script>
           
            <!--========== SCROLL REVEAL ==========-->
            <script src="https://unpkg.com/scrollreveal"></script>
            
            <!--========== MAIN JS ==========-->
            <script src="{% static 'js/main.js' %}"></script>
            <script>
                let slideIndex = 0;
                        showSlides();
            
                        function showSlides() {
                         let i;
                        let slides = document.getElementsByClassName("mySlides");
                        for (i = 0; i < slides.length; i++) {
                        slides[i].style.display = "none";
                        }
                        slideIndex++;
                         if (slideIndex > slides.length) {slideIndex = 1}
                        slides[slideIndex-1].style.display = "block";
                        setTimeout(showSlides, 3000); // Change image every 2 seconds
                        }
            </script>
</body>
</html>
    

templates/booking.html
{% load static %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

/* input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
} */

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
  color:black;
  width:50%;
  margin-left:25%;
}

</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
  {% include 'header.html' %}
  <br><br><br><br><br>


<div class="container">
  <center><h3>Event Book</h3></center>
  <form action="" method="POST">
    {% csrf_token %}
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors  %}
            <script>alert("{{error}}")</script>
        {% endfor %}
        {% endif %}
        <hr>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="Name">Name</label>
            <input type="text" class="form-control" required value="{{data.first_name}} {{data.last_name}}"readonly>
          </div>
          <div class="form-group col-md-6">
            <label for="Email">Email-Id</label>
            <input type="email" class="form-control" required value="{{data.email}}" readonly >
          </div>
        </div> 
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="Event_Name">Event Name</label>
            <input type="text" class="form-control"name="Event_Name" maxlength="50" required id="id_Event_Name">
          </div>
          <div class="form-group col-md-6">
            <label for="Contact">Contact Number</label>
            <input type="tel" class="form-control"name="Number" maxlength="10" required id="id_Number">
          </div>
        </div> 
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="date">Event Date</label>
            <input type="date" class="form-control"name="Date"required id="id_date">
          </div>
          <div class="form-group col-md-6">
            <label for="Guest">Total Guest</label>
            <input type="number" class="form-control"name="Guest" required id="id_Guest">
          </div>
        </div> 
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="Venue">Event Venue</label>
            <input type="text" class="form-control"name="Venue"required id="id_venue">
          </div>
          <div class="form-group col-md-6">
            <label for="Day">Total Day</label>
            <input type="number" class="form-control"name="Day" required id="id_Day">
          </div>
        </div> 
   
            
        
    <center><button type="submit" class="btn btn-success">Submit</button></center>

    
  </form>
</div>

</body>
</html>

templates/bookingstatus.html
{%load static%}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
    
    
      <style media="screen">
        a:link {
          text-decoration: none;
        }
    
        h6 {
          text-align: center;
        }
    
        .row {
          margin: 100px;
        }
      </style>
    </head>
    <body>
      {% if messages %}
      {% for message in messages %}
       {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

      {% endfor %}

  {% endif %}
        {% include 'header.html' %}
        <br><br><br>
    <div class="container">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 style="color:white;" class="panel-title text-center"><b>Booking Status</b></h2><br><br>
        </div>
        <table class="table table-hover" id="dev-table">
          <thead>
            <tr class="bg-success">
    
              <th>Name</th>
              
              <th>Contact Number</th>
              <th>Function</th>
              <th>Date</th>
              <th>Status</th>
              <th><center>Cancel Booking</center></th>
              
            </tr>
          </thead>
          {% for t in data %}
          <tr class="table-success">
    
            <td><b> {{t.user.first_name}}<b></td>
            <td><b> {{t.number}}<b></td>
            <td><b>{{t.f_name}}<b></td>
            <td><b>{{t.date}}<b></td>
            <td><b>{{t.status}}<b></td>
                <td><center><a class="btn btn-danger btn-xs" href="{% url 'delete_booking' t.id  %}"><i class="fas fa-trash"></i></a></center></td>
          {% endfor %}
        </table>
      </div>
    </div>
    <br><br><br><br>
</body>
{% comment %} {% include 'admin/footer.html' %} {% endcomment %}

templates/contact.html
{% load static %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
  color:black;
  width:50%;
  margin-left:25%;
}
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
  {% include 'base.html' %}
  <br><br><br><br><br>


<div class="container">
  <center><h3>Contact Form</h3></center>
  <form action="" method="POST">
    {% csrf_token %}
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors  %}
            <script>alert("{{error}}")</script>
        {% endfor %}
        {% endif %}
        {% for fm in form  %}
            {{fm.label_tag}} {{fm}} {{fm.error|striptags}}
        {% endfor %}
        
    <center><button type="submit" class="btn btn-success">Submit</button></center>

    
  </form>
</div>

</body>
</html>

      {% include 'footer.html' %}
</body>
</html>

templates/dashboard.html
{% load static %}
{% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %}
{% include 'base.html' %}
{% comment %} <main class="l-main"> {% endcomment %}
    <!--========== SIGN IN ==========-->
   
    <!--========== HOME ==========-->
    <section class="home" id="home">
        <div class="home__container bd-container bd-grid">
            <div class="home__data">
                <h1 class="home__title">Tasty food</h1>
                <h2 class="home__subtitle">Try the best food of <br> the week.</h2>
                <a href="/menu" class="button">View Menu</a>
            </div>

            <img src="{% static 'img/home.png' %}" alt="" class="home__img">
        </div>
    </section>
    
{% include  'footer.html'%}

templates/event.html
<!DOCTYPE html>
{% load static %}
{% include "header.html" %}
<br><br><br>
<html lang="en">
<head>
    
    <title>Event</title>
</head>
<style>
    body{
    font-family: 'Poppins', sans-serif;
    color: black;
    background-image: url('foodimage/cloud.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    }
    .main_container{
        display: flex;
        justify-content: space-around;
    }
    .card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  border-radius: 16px;
}
.card img{
    width:300px;
    height: 300px;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
  background-color: antiquewhite;
}
.heading p{
    font-size: 70px;
    text-align: center;
    font-weight: bold;
    
}
</style>
<body>
    <div class="heading">
        <p>Our Events</p>
    </div>
    <div class="main_container">
        <div class="card">
            <img src="{% static 'foodimage/birthday.jpg' %}" alt="Avatar">
            <div class="container">
              <h4><b>Birthday Party</b></h4>
              <p></p>
            </div>
          </div>
          <div class="card">
            <img src="{% static 'foodimage/ring.jpg' %}" alt="Avatar">
            <div class="container">
              <h4><b>Ring Ceremony</b></h4>
              <p></p>
            </div>
          </div>
          <div class="card">
            <img src="{% static 'foodimage/college.jpg' %}" alt="Avatar">
            <div class="container">
              <h4><b>College Events</b></h4>
              <p></p>
            </div>
          </div>
          <div class="card">
            <img src="{% static 'foodimage/Receptions.jpg' %}" alt="Avatar">
            <div class="container">
              <h4><b>Receptions Party</b></h4>
              <p></p>
            </div>
          </div>
    </div>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<head>
    <link rel="stylesheet" href="assets/css/styles.css">
</head>
<footer class="footer section bd-container">
    <div class="footer__container bd-grid">
        <div class="footer__content">
            <a href="#" class="footer__logo">Tasty Food</a>
            <span class="footer__description">Restaurant</span>
            <div>
                <a href="#" class="footer__social"><i class='bx bxl-facebook'></i></a>
                <a href="#" class="footer__social"><i class='bx bxl-instagram'></i></a>
                <a href="#" class="footer__social"><i class='bx bxl-twitter'></i></a>
            </div>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Services</h3>
            <ul>
                <li><a href="#" class="footer__link">Delivery</a></li>
                <li><a href="#" class="footer__link">Pricing</a></li>
                <li><a href="#" class="footer__link">Fast food</a></li>
                <li><a href="#" class="footer__link">Reserve your spot</a></li>
            </ul>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Information</h3>
            <ul>
                <li><a href="#" class="footer__link">Event</a></li>
                <li><a href="#" class="footer__link">Contact us</a></li>
                <li><a href="#" class="footer__link">Privacy policy</a></li>
                <li><a href="#" class="footer__link">Terms of services</a></li>
            </ul>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Adress</h3>
            <ul>
                <li>Jaypath Nagar</li>
                <li>999 - 888 - 777</li>
                <li>tastyfood@email.com</li>
            </ul>
        </div>
    </div>
    <p class="footer__copy">&#169; 2022, All right reserved</p>
</footer>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href='{% static "css/styles.css" %}'>
    <title>Document</title>
</head>
<body>
    <a href="#" class="scrolltop" id="scroll-top">
        <i class='bx bx-chevron-up scrolltop__icon'></i>
    </a>
<header class="l-header" id="header">
            <nav class="nav bd-container">
                <a href="/home" class="nav__logo">Tasty</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="/home" class="nav__link active-link">Home</a></li>
                        <li class="nav__item"><a href="/service" class="nav__link">Services</a></li>
                        <li class="nav__item"><a href="/menu" class="nav__link">Menu</a></li>
                        <li class="nav__item"><a href="/event" class="nav__link">Events</a></li>
                        <li class="nav__item"><a href="/booking" class="nav__link">Booking</a></li>
                        <li class="nav__item"><a href="/bookingstatus" class="nav__link">Booking Status</a></li>
                        <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link">Logout</a></li>

                        <li><i class='bx bx-moon change-theme' id="theme-button"></i></li>
                        {% comment %} <li><h6>Welcome {{name}}</h6></li> {% endcomment %}
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
            </header>
            <script src="{% static 'js/main.js' %}"></script>
            <a href="https://chat.whatsapp.com/EVnVqRYWxP99ymIPjIyJBA" class="whats-app" href="#">
                <span><svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1.1" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" class="my-float"><path d="M13.641 2.325c-1.497-1.5-3.488-2.325-5.609-2.325-4.369 0-7.925 3.556-7.925 7.928 0 1.397 0.366 2.763 1.059 3.963l-1.125 4.109 4.203-1.103c1.159 0.631 2.463 0.966 3.787 0.966h0.003c0 0 0 0 0 0 4.369 0 7.928-3.556 7.928-7.928 0-2.119-0.825-4.109-2.322-5.609zM8.034 14.525v0c-1.184 0-2.344-0.319-3.356-0.919l-0.241-0.144-2.494 0.653 0.666-2.431-0.156-0.25c-0.663-1.047-1.009-2.259-1.009-3.506 0-3.634 2.956-6.591 6.594-6.591 1.759 0 3.416 0.688 4.659 1.931 1.244 1.247 1.928 2.9 1.928 4.662-0.003 3.637-2.959 6.594-6.591 6.594zM11.647 9.588c-0.197-0.1-1.172-0.578-1.353-0.644s-0.313-0.1-0.447 0.1c-0.131 0.197-0.512 0.644-0.628 0.778-0.116 0.131-0.231 0.15-0.428 0.050s-0.838-0.309-1.594-0.984c-0.588-0.525-0.987-1.175-1.103-1.372s-0.013-0.306 0.088-0.403c0.091-0.088 0.197-0.231 0.297-0.347s0.131-0.197 0.197-0.331c0.066-0.131 0.034-0.247-0.016-0.347s-0.447-1.075-0.609-1.472c-0.159-0.388-0.325-0.334-0.447-0.341-0.116-0.006-0.247-0.006-0.378-0.006s-0.347 0.050-0.528 0.247c-0.181 0.197-0.694 0.678-0.694 1.653s0.709 1.916 0.809 2.050c0.1 0.131 1.397 2.134 3.384 2.991 0.472 0.203 0.841 0.325 1.128 0.419 0.475 0.15 0.906 0.128 1.247 0.078 0.381-0.056 1.172-0.478 1.338-0.941s0.166-0.859 0.116-0.941c-0.047-0.088-0.178-0.137-0.378-0.238z"></path></svg></span>
            </a>
            <!--========== SCROLL REVEAL ==========-->
            <script src="https://unpkg.com/scrollreveal"></script>
            
            <!--========== MAIN JS ==========-->
            <script src="{% static 'js/main.js' %}"></script>
            <script>
                let slideIndex = 0;
                        showSlides();
            
                        function showSlides() {
                         let i;
                        let slides = document.getElementsByClassName("mySlides");
                        for (i = 0; i < slides.length; i++) {
                        slides[i].style.display = "none";
                        }
                        slideIndex++;
                         if (slideIndex > slides.length) {slideIndex = 1}
                        slides[slideIndex-1].style.display = "block";
                        setTimeout(showSlides, 3000); // Change image every 2 seconds
                        }
            </script>
</body>
</html>
    

templates/login.html
{% load static %}
{% include "base.html" %}
<head>
    {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %}
</head>
</html>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

img.avatar {
  width: 80px;
  border-radius: 50%;
}

.container {
  padding: 16px;
 
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
  .con{
    display: flex;
    /* justify-content: center; */
    /* justify-items: center; */

    align-items: center;
  }
}
</style>
</head>
<body>
<br><br><br><br>
<center><h2>Login Form</h2></center><br>
<div class="con">
<form action="" method="POST" style="width: 50%; margin-left: 25%;" >
  <div class="imgcontainer">
    <img src="{% static 'img_avatar2.png' %}" alt="Avatar" class="avatar">
  </div>

  <div class="container">
    {% csrf_token %}
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors  %}
            <script>alert("{{error}}")</script>
        {% endfor %}
        {% endif %}
        {% for fm in form  %}
            {{fm.label_tag}} {{fm}} {{fm.error|striptags}}<br><br>
        {% endfor %}
        
    <button type="submit">Login</button>
  </div>
</form>
</div>
{% include  'footer.html'%}
</body>
</html>